// <auto-generated />
using System;
using HexManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HexManager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("HexManager.Models.TrafficSignal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AreaNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtcsCurrentBiuSerialNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtcsCurrentCabSerialNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtcsCurrentCmSerialNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtcsCurrentCpuSerialNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtcsCurrentDciSerialNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AtcsCurrentPdaSerialNum")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuxiliaryCabinetsNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BatteryBackupModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BatteryLastChanged")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BbsChangeScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BbsMake")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BbsModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BbsNextChangeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("BbsScheduleGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Boro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoastalFoundations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ComputerFlag")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractorReferenceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControllerCleaningEmployee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ControllerCompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ControllerDialNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ControllerDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ControllerLoopNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControllerLoopType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControllerNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ControllerScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ControllerSerialNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ControllerType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountdownPeds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cylinders")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("D14LedLamps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("D5LedLamps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("D712InLedLamps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("D78InLedLamps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeoKey1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeoKeyStreet1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GeoKeyStreet2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HexAddress")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<string>("KeyBIP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("L116Lamps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("L150Lamps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("L67Lamps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("L68Lamps")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LampingEmployee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("LedPeds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogicalNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoopQty")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("M2Poles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MappingX")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MappingY")
                        .HasColumnType("TEXT");

                    b.Property<string>("MoxaCMWN")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MoxaIMEI")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OnLine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaintStartDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaintingCompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaintingDueDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaintingEmployee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaintingHardware")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaintingRods")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PaintingScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaintingStartEmployee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PoleType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PoliceCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProblemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RedlightCameraInstallDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RedlightCameraRemoveDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("RedlightCameraType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RelampingCompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RelampingDueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RelampingScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("S1Poles")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SegmentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SequenceNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SignalInstallDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SignalType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StrayVoltageCheckCompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StrayVoltageCheckDueDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StrayVoltageCheckScheduledDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("StrayVoltageInspectionComments")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrayVoltageOpenWorkOrder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetCode1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetCode2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetCode3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetCode4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetName1")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetName2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetName3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StreetName4")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TsmpIntersectionControlNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Boro")
                        .HasDatabaseName("IX_TrafficSignals_Boro");

                    b.HasIndex("HexAddress")
                        .IsUnique()
                        .HasDatabaseName("IX_TrafficSignals_HexAddress");

                    b.HasIndex("StreetName1", "StreetName2")
                        .HasDatabaseName("IX_TrafficSignals_Streets");

                    b.ToTable("TrafficSignals");
                });
#pragma warning restore 612, 618
        }
    }
}
